name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg

      - uses: actions/deploy-pages@v1
        if: success()
        with:
          artifact_name: snake-animation
